import 'package:flutter/material.dart';
import 'services/app_store.dart';
import 'screens/dashboard_screen.dart';
import 'screens/projects_screen.dart';
import 'screens/tasks_screen.dart';
import 'screens/notes_screen.dart';
import 'screens/insights_screen.dart';

void main(){WidgetsFlutterBinding.ensureInitialized();runApp(const ChronicleApp());}
class ChronicleApp extends StatefulWidget{const ChronicleApp({super.key});@override State<ChronicleApp> createState()=>_ChronicleAppState();}
class _ChronicleAppState extends State<ChronicleApp>{final store=AppStore();@override void initState(){super.initState();store.load();}@override Widget build(BuildContext context)=>AnimatedBuilder(animation:store,builder:(_,__)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Chronicle',themeMode:ThemeMode.system,theme:_theme(Brightness.light),darkTheme:_theme(Brightness.dark),home:store.ready?HomeShell(store:store):const Scaffold(body:Center(child:CircularProgressIndicator()))));ThemeData _theme(Brightness b){final cs=ColorScheme.fromSeed(seedColor:const Color(0xFF6750A4),brightness:b);return ThemeData(useMaterial3:true,colorScheme:cs,scaffoldBackgroundColor:b==Brightness.light?const Color(0xFFF8F7FC):const Color(0xFF111116),appBarTheme:const AppBarTheme(centerTitle:false),cardTheme:CardThemeData(elevation:0,margin:EdgeInsets.zero,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22)),color:b==Brightness.light?Colors.white:const Color(0xFF1B1B22)),inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:b==Brightness.light?const Color(0xFFF1EFF7):const Color(0xFF24242C),border:OutlineInputBorder(borderSide:BorderSide.none,borderRadius:BorderRadius.circular(16))));}}
class HomeShell extends StatefulWidget{const HomeShell({super.key,required this.store});final AppStore store;@override State<HomeShell> createState()=>_HomeShellState();}
class _HomeShellState extends State<HomeShell>{int index=0;@override Widget build(BuildContext context){final pages=[DashboardScreen(store:widget.store,onOpenTask:(_){setState(()=>index=2);},onStart:_start),ProjectsScreen(store:widget.store),TasksScreen(store:widget.store),NotesScreen(store:widget.store),InsightsScreen(store:widget.store)];return Scaffold(body:IndexedStack(index:index,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const [NavigationDestination(icon:Icon(Icons.space_dashboard_outlined),selectedIcon:Icon(Icons.space_dashboard_rounded),label:'Сегодня'),NavigationDestination(icon:Icon(Icons.folder_outlined),selectedIcon:Icon(Icons.folder_rounded),label:'Проекты'),NavigationDestination(icon:Icon(Icons.checklist_outlined),selectedIcon:Icon(Icons.checklist_rounded),label:'Задачи'),NavigationDestination(icon:Icon(Icons.menu_book_outlined),selectedIcon:Icon(Icons.menu_book_rounded),label:'Заметки'),NavigationDestination(icon:Icon(Icons.insights_outlined),selectedIcon:Icon(Icons.insights_rounded),label:'Отчёты')]));}
Future<void> _start()async{final c=TextEditingController();String pid=widget.store.data.projects.first.id;await showModalBottomSheet(context:context,isScrollControlled:true,builder:(ctx)=>Padding(padding:EdgeInsets.fromLTRB(20,22,20,MediaQuery.viewInsetsOf(ctx).bottom+24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Начать работу',style:Theme.of(ctx).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:16),TextField(controller:c,autofocus:true,decoration:const InputDecoration(labelText:'Над чем работаешь?')),const SizedBox(height:12),DropdownButtonFormField(initialValue:pid,items:widget.store.data.projects.map((p)=>DropdownMenuItem(value:p.id,child:Text('${p.emoji} ${p.title}'))).toList(),onChanged:(v)=>pid=v!),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:(){widget.store.startTimer(description:c.text.trim(),projectId:pid);Navigator.pop(ctx);},icon:const Icon(Icons.play_arrow_rounded),label:const Text('Запустить таймер')))])));}}
