import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_math_fork/flutter_math.dart';
import 'package:uuid/uuid.dart';
import '../models/app_models.dart';
import '../services/app_store.dart';

class NotesScreen extends StatefulWidget { const NotesScreen({super.key, required this.store}); final AppStore store; @override State<NotesScreen> createState()=>_NotesScreenState(); }
class _NotesScreenState extends State<NotesScreen>{ String query=''; @override Widget build(BuildContext context){ final notes=widget.store.data.notes.where((n)=>n.title.toLowerCase().contains(query.toLowerCase())||n.body.toLowerCase().contains(query.toLowerCase())).toList(); return Scaffold(appBar:AppBar(title:const Text('Заметки'),actions:[IconButton(onPressed:_add,icon:const Icon(Icons.note_add_outlined))]),body:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,8,16,8),child:SearchBar(hintText:'Поиск по базе знаний',leading:const Icon(Icons.search_rounded),onChanged:(v)=>setState(()=>query=v))),Expanded(child:ListView.separated(padding:const EdgeInsets.fromLTRB(16,8,16,100),itemCount:notes.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){final n=notes[i];final p=widget.store.data.projects.firstWhere((p)=>p.id==n.projectId);return Card(child:ListTile(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>NoteEditor(store:widget.store,note:n))),leading:CircleAvatar(child:Text(p.emoji)),title:Text(n.title),subtitle:Text('${n.tags.map((e)=>'#$e').join(' ')}\nОбновлено ${n.updatedAt.day}.${n.updatedAt.month}',maxLines:2),isThreeLine:true,trailing:const Icon(Icons.chevron_right_rounded)));}))])); }
  void _add(){final p=widget.store.data.projects.first;final n=Note(id:const Uuid().v4(),title:'Новая заметка',projectId:p.id,body:'# Новая заметка\n\n');widget.store.addNote(n);Navigator.push(context,MaterialPageRoute(builder:(_)=>NoteEditor(store:widget.store,note:n))).then((_)=>setState((){}));}
}

class NoteEditor extends StatefulWidget { const NoteEditor({super.key,required this.store,required this.note}); final AppStore store; final Note note; @override State<NoteEditor> createState()=>_NoteEditorState(); }
class _NoteEditorState extends State<NoteEditor>{ late TextEditingController title;late TextEditingController body;bool preview=false; @override void initState(){super.initState();title=TextEditingController(text:widget.note.title);body=TextEditingController(text:widget.note.body);} void save(){widget.note.title=title.text.trim().isEmpty?'Без названия':title.text.trim();widget.note.body=body.text;widget.note.updatedAt=DateTime.now();widget.store.changed();}
  @override Widget build(BuildContext context)=>PopScope(onPopInvokedWithResult:(_,__)=>save(),child:Scaffold(appBar:AppBar(actions:[IconButton(onPressed:(){save();setState(()=>preview=!preview);},icon:Icon(preview?Icons.edit_rounded:Icons.visibility_outlined)),PopupMenuButton(itemBuilder:(_)=>[const PopupMenuItem(value:'delete',child:Text('Удалить'))],onSelected:(v){if(v=='delete'){widget.store.deleteNote(widget.note.id);Navigator.pop(context);}})]),floatingActionButton:FloatingActionButton.extended(onPressed:(){save();widget.store.startTimer(description:'Работа над ${widget.note.title}',projectId:widget.note.projectId,noteId:widget.note.id);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Таймер запущен')));},icon:const Icon(Icons.play_arrow_rounded),label:const Text('Работать')),body:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.symmetric(horizontal:18),child:TextField(controller:title,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w700),decoration:const InputDecoration(border:InputBorder.none,hintText:'Название'))),const Divider(height:1),Expanded(child:preview?_Preview(data:body.text):TextField(controller:body,expands:true,maxLines:null,minLines:null,textAlignVertical:TextAlignVertical.top,style:const TextStyle(fontFamily:'monospace',fontSize:15,height:1.55),decoration:const InputDecoration(contentPadding:EdgeInsets.all(18),border:InputBorder.none,hintText:'Markdown, LaTeX, [[ссылки]]…')))]))));}
class _Preview extends StatelessWidget{const _Preview({required this.data});final String data;@override Widget build(BuildContext context){final parts=data.split(RegExp(r'(\\\[[\s\S]*?\\\]|\$\$[\s\S]*?\$\$)'));return ListView(padding:const EdgeInsets.fromLTRB(20,18,20,120),children:parts.where((e)=>e.isNotEmpty).map((e){final t=e.trim();if((t.startsWith(r'\[')&&t.endsWith(r'\]'))||(t.startsWith(r'$$')&&t.endsWith(r'$$'))){final tex=t.startsWith(r'\[')?t.substring(2,t.length-2):t.substring(2,t.length-2);return Padding(padding:const EdgeInsets.symmetric(vertical:12),child:SingleChildScrollView(scrollDirection:Axis.horizontal,child:Math.tex(tex,textStyle:Theme.of(context).textTheme.titleMedium)));}return MarkdownBody(data:e,selectable:true);}).toList());}}
